import type { Metadata } from "next";
import {Noto_Sans_KR  , Poppins ,Geist } from "next/font/google";
import  {cn} from "@/lib/utils";

import "./globals.css";

// 폰트 설정
const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["400","500","600","700","800","900"], // 필요한 가중치 추가
})

const poppins=Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`
            ${cn(notoSansKR.className, "dark")} 
            ${cn(poppins.className, "dark")}
            ${cn(geistSans.className, "dark")}
            antialiased`
        } > 
         
      {/* <body className={cn(notoSansKR.className, "dark")} >
      */}
        {children}
      </body>

    </html>
  );
}
